"""empty message

Revision ID: 849128cdb118
Revises: ee94eeabd3a3
Create Date: 2021-03-31 16:14:33.463214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849128cdb118'
down_revision = 'ee94eeabd3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_SW',
    sa.Column('id_favorite', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('planets_id_fk', sa.Integer(), nullable=False),
    sa.Column('people_id_fk', sa.Integer(), nullable=False),
    sa.Column('type_favorite', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_favorite')
    )
    op.create_table('people_SW',
    sa.Column('id_people', sa.Integer(), nullable=False),
    sa.Column('people_height', sa.Integer(), nullable=False),
    sa.Column('people_mass', sa.Integer(), nullable=False),
    sa.Column('people_hair_color', sa.String(length=250), nullable=False),
    sa.Column('people_skin_color', sa.String(length=250), nullable=False),
    sa.Column('people_eye_color', sa.String(length=250), nullable=False),
    sa.Column('people_birth_year', sa.String(length=250), nullable=False),
    sa.Column('people_gender', sa.String(length=250), nullable=False),
    sa.Column('people_created', sa.String(length=250), nullable=False),
    sa.Column('people_edited', sa.String(length=250), nullable=False),
    sa.Column('people_name', sa.String(length=250), nullable=False),
    sa.Column('people_homeworld', sa.String(length=250), nullable=False),
    sa.Column('people_url', sa.String(length=250), nullable=False),
    sa.Column('planets_id_fk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_people')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people_SW')
    op.drop_table('favorite_SW')
    # ### end Alembic commands ###
