"""empty message

Revision ID: 89d40848e81d
Revises: bb72b6ff1ee1
Create Date: 2021-04-01 02:07:35.954771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89d40848e81d'
down_revision = 'bb72b6ff1ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people_sw', 'planets_id_fk',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people_sw', 'planets_id_fk',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
