"""empty message

Revision ID: ee94eeabd3a3
Revises: 8b6f5fad6ff2
Create Date: 2021-03-31 15:33:25.157853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee94eeabd3a3'
down_revision = '8b6f5fad6ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets_SW',
    sa.Column('id_planets', sa.Integer(), nullable=False),
    sa.Column('planets_name', sa.String(length=250), nullable=False),
    sa.Column('planets_diameter', sa.Integer(), nullable=False),
    sa.Column('planets_rotation_period', sa.Integer(), nullable=False),
    sa.Column('planets_orbital_period', sa.Integer(), nullable=False),
    sa.Column('planets_gravity', sa.String(length=250), nullable=False),
    sa.Column('planets_population', sa.Integer(), nullable=False),
    sa.Column('planets_climate', sa.String(length=250), nullable=False),
    sa.Column('planets_terrain', sa.String(length=250), nullable=False),
    sa.Column('planets_surface_water', sa.Integer(), nullable=False),
    sa.Column('planets_created', sa.String(length=250), nullable=False),
    sa.Column('planets_edited', sa.String(length=250), nullable=False),
    sa.Column('planets_url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_planets')
    )
    op.create_table('user_SW',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name_user', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email_user', sa.String(length=250), nullable=False),
    sa.Column('birth_user', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_SW')
    op.drop_table('planets_SW')
    # ### end Alembic commands ###
